feat: DEVOPS-141 service cache function on io-infra migration
pagopa/io-infra pull request #129
Opened 2022-03-07 16:57 UTC by diegolagospagopa

### List of changes

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Env to apply

- [ ] DEV
- [ ] UAT
- [ ] PROD

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

### How to apply

After PR is approved
1. run deploy pipeline from Azure DevOps [io-infra.deploy](https://dev.azure.com/pagopaspa/io-iac-projects/_build?definitionId=218)
2. select PR branch
3. wait for approval

2022-03-07 17:03 UTC, balanza reviewed
We have never used the naming pattern _XX_name.tf_. I see the value in order to sort files, I just won't introduce such formalism only for a small set of files. Maybe we can propose such refactor in a dedicated PR

2022-03-08 09:08 UTC, pasqualedevita requested changes
LGTM, only rename in services-cache (final s)

2022-03-08 09:08 UTC, pasqualedevita commented on src/core/env/prod/terraform.tfvars
> +cidr_subnet_fn_service_cache   = ["10.0.125.0/24"]
```suggestion
cidr_subnet_fn_service_cache   = ["10.0.129.0/24"]
```

2022-03-08 09:09 UTC, pasqualedevita commented on src/core/env/prod/terraform.tfvars
> +cidr_subnet_fn_service_cache   = ["10.0.125.0/24"]
10.0.125.0 is the actual subnet and we have a conflict

2022-03-08 15:13 UTC, diegolagospagopa commented
> We have never used the naming pattern _XX_name.tf_. I see the value in order to sort files, I just won't introduce such formalism only for a small set of files. Maybe we can propose such refactor in a dedicated PR

Removed files with data, we can think in future to have a xx_name.tf to simplify the use of the project

2022-03-10 08:52 UTC, pasqualedevita submitted a review, later dismissed

2022-03-14 12:38 UTC, merged