Add table column for requireSecureChannels field on DeveloperPortalSe…
pagopa/io-infra pull request #263
Opened 2022-10-13 14:02 UTC by LoFrance

We need to have `requireSecureChannels` in our PSQL db, this PR alter the original schema and add a new column of boolean type.

### List of changes

### Motivation and context

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Env to apply

- [ ] DEV
- [ ] UAT
- [ ] PROD

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

### How to apply

After PR is approved
1. run deploy pipeline from Azure DevOps [io-platform-iac-projects](https://dev.azure.com/pagopaspa/io-platform-iac-projects/_build?view=folders)
2. select PR branch
3. wait for approval

2022-10-13 14:25 UTC, pasqualedevita approved these changes

2022-10-13 14:26 UTC, pasqualedevita requested changes
Maybe you need a double __ in file name

2022-10-14 13:20 UTC, LoFrance commented
> Maybe you need a double __ in file name

Fix with 1e7aea3

2022-10-14 14:49 UTC, pasqualedevita approved these changes

2022-10-17 14:50 UTC, merged