chore(io-sign): [SFEQS-1263] Remove unused queue
pagopa/io-infra pull request #346
Opened 2022-12-19 14:20 UTC by lucacavallaro

### List of changes

### Motivation and context

The `waiting-message` queue is not used

### Type of changes

- [ ] Add new resources
- [ ] Update configuration to existing resources
- [x] Remove existing resources

### Env to apply

- [ ] DEV
- [ ] UAT
- [x] PROD

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

### How to apply

After PR is approved
1. run deploy pipeline from Azure DevOps [io-platform-iac-projects](https://dev.azure.com/pagopaspa/io-platform-iac-projects/_build?view=folders)
2. select PR branch
3. wait for approval

2022-12-19 14:45 UTC, manuelcoppotelli commented
Depends on #348

2022-12-21 07:27 UTC, pasqualedevita approved these changes

2022-12-21 07:33 UTC, pasqualedevita requested changes
strange error in the ci/cd... try to update branch

2022-12-21 08:13 UTC, manuelcoppotelli commented
@pasqualedevita fixed

2022-12-22 11:56 UTC, pasqualedevita approved these changes

2022-12-22 14:03 UTC, merged