[#IC-115] Create resources for `Selfcare IO`
pagopa/io-infra pull request #55
Opened 2021-12-13 16:16 UTC by balanza

Co-authored-by: Diego Lagos <diegolagospagopa@users.noreply.github.com>

### List of changes

* create a new storage account to contain built frontend artifact
* expose frontend artifacts through a CDN
* create an app service instance to contain backend node application

### Motivation and context

Will create resources in order to have an instance of `SelfCare IO` portal. DNS records and Api Gateway/Api Management set up is out of the scope for this PR
![inf](https://user-images.githubusercontent.com/265564/145847692-c91e1eae-1078-49a1-bf6c-60d866678580.png)

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Env to apply

- [ ] DEV
- [ ] UAT
- [x] PROD

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2021-12-15 13:12 UTC, balanza commented
/azp run

2021-12-15 15:29 UTC, pasqualedevita requested changes

2021-12-15 15:29 UTC, pasqualedevita commented on src/core/env/prod/terraform.tfvars
> +cidr_subnet_selfcare_fe_storage = ["10.0.137.0/24"]
front end storage not need subnet

2021-12-15 15:29 UTC, pasqualedevita commented on src/core/selfcare_be.tf
> +  ftps_state = "AllAllowed"
```suggestion
```
????

2021-12-15 15:29 UTC, pasqualedevita commented on src/core/selfcare_be.tf
> +  plan_kind     = var.app_service_plan_kind
```suggestion
  plan_kind     = "Linux"
  plan_reserved = true
```
use only linux plans for cost savings.
when we use linux we need also to set

`plan_reserved = true # Mandatory for Linux plan`

ref. https://github.com/pagopa/pagopa-infra/blob/main/src/mock_ec.tf#L28

2021-12-15 15:29 UTC, pasqualedevita commented on src/core/selfcare_be.tf
> +  name = "${var.location}-${var.env_short}"
```suggestion
  name = format("%s-app-devportal-be", local.project)
```
missing app service name
we don't use location but we can introduce it. Better to add a `var.location_short`

2021-12-15 15:29 UTC, pasqualedevita commented on src/core/selfcare_be.tf
> +  plan_kind     = var.app_service_plan_kind
better to use specific var names, for example

devportal_plan_sku
devportal_plan_sku_tier
devportal_plan_kind

2021-12-15 15:29 UTC, pasqualedevita commented on src/core/selfcare_be.tf
> +    WEBSITE_NPM_DEFAULT_VERSION  = "6.1.0"
node 6?

2021-12-15 15:51 UTC, balanza commented on src/core/selfcare_be.tf
> +    WEBSITE_NPM_DEFAULT_VERSION  = "6.1.0"
Same as https://github.com/pagopa/io-infrastructure-live-new/blob/25bbedf15cb03fa78a10d910303f98337df8522f/prod/westeurope/internal/developerportalbackend/app_service/terragrunt.hcl#L60

2021-12-16 18:07 UTC, pasqualedevita approved these changes

2021-12-16 19:08 UTC, merged