[#IC-160] Implement jwk signature verification on `SelfCare IO` (cleanup)
pagopa/io-infra pull request #68
Opened 2021-12-29 11:42 UTC by balanza

Cleanup unused `SELFCARE_IDP_ISSUER_JWT_SIGNATURE_KEY` env var.

To be applied and merged after https://github.com/pagopa/io-developer-portal-backend/pull/152 and https://github.com/pagopa/io-infra/pull/67 are deployed

2021-12-29 17:05 UTC, pasqualedevita requested changes
remove also

```
data "azurerm_key_vault_secret" "selfcare_selfcare_idp_issuer_jwt_signature_key" {
  name         = "selfcare-SELFCARE-IDP-ISSUER-JWT-SIGNATURE-KEY"
  key_vault_id = data.azurerm_key_vault.common.id
}
```

```
data "http" "selfcare_well_known_jwks_json" {
  url = "https://${local.selfcare.hostname}/.well-known/jwks.json"
  # Optional request headers
  request_headers = {
    Accept = "application/json"
  }
}
```

2021-12-29 17:13 UTC, balanza commented
@pasqualedevita `selfcare_well_known_jwks_json` is actually used by `SELFCARE_JWKS_URL`

2021-12-30 07:09 UTC, pasqualedevita approved these changes

2021-12-30 07:57 UTC, pasqualedevita requested changes

2021-12-30 07:57 UTC, pasqualedevita commented on src/core/selfcare.tf
> +    SELFCARE_LOGIN_URL  = "${local.selfcare.hostname}/auth/login"
```suggestion
    SELFCARE_LOGIN_URL  = "https://${local.selfcare.hostname}/auth/login"
```

2021-12-30 07:58 UTC, pasqualedevita approved these changes

2021-12-30 08:06 UTC, merged