[#IOPID-1195] add IO-WEB profile invalid unlock codes alert
pagopa/io-infra pull request #828
Opened 2024-01-11 11:05 UTC by arcogabbo

### List of changes
* [[#IOPID-1195] added alert](https://github.com/pagopa/io-infra/commit/1eed33e4ed6feaf89dac3d03437215d6db6e4aa0)

### Motivation and context
Add an alert that fires when a lot of invalid codes are submitted to IO-WEB profile unlock endpoint

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Env to apply

- [ ] DEV
- [ ] UAT
- [x] PROD

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

### How to apply

After PR is approved
1. run deploy pipeline from Azure DevOps [io-platform-iac-projects](https://dev.azure.com/pagopaspa/io-platform-iac-projects/_build?view=folders)
2. select PR branch
3. wait for approval

2024-01-18 09:29 UTC, gquadrati requested changes

2024-01-18 09:29 UTC, gquadrati commented on src/domains/ioweb-app/06_function_ioweb_profile.tf
> +  severity            = 3
```suggestion
  severity            = 1
```

2024-01-18 09:29 UTC, gquadrati commented on src/domains/ioweb-app/06_function_ioweb_profile.tf
> +  description         = "A lot of invalid codes submitted to IO-WEB profile unlock functionality"
```suggestion
  description         = "Too many of invalid codes submitted to IO-WEB profile unlock functionality"
```

2024-01-18 09:29 UTC, gquadrati commented on src/domains/ioweb-app/06_function_ioweb_profile.tf
> +  }
I'd go for a more granular check:

```suggestion
  window_size         = "PT15M"
  frequency           = "PT5M"
  auto_mitigate       = false


  # Metric info
  # https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-web-sites-metrics
  dynamic_criteria {
    metric_namespace         = "Microsoft.Web/sites"
    metric_name              = "Http401"
    aggregation              = "Total"
    operator                 = "GreaterThan"
    alert_sensitivity        = "Medium"
    evaluation_total_count   = 4
    evaluation_failure_count = 1
    skip_metric_validation   = false
  }
```

2024-01-19 14:02 UTC, BurnedMarshal commented on src/domains/ioweb-app/06_function_ioweb_profile.tf
> +| where url contains "unlock-session"
We can optimize the query using `==` instead `contains`. [ref](https://learn.microsoft.com/it-it/azure/data-explorer/kusto/query/datatypes-string-operators#performance-tips)
```suggestion
| where name == "UnlockSession"
```

2024-01-19 14:45 UTC, arcogabbo commented on src/domains/ioweb-app/06_function_ioweb_profile.tf
> +  scopes                  = [module.function_ioweb_profile.id]
nice suggestion, thank you. done in https://github.com/pagopa/io-infra/pull/828/commits/79c045310d6c3222206cf0b33abee89715c76962

2024-01-19 16:09 UTC, BurnedMarshal approved these changes

2024-01-19 16:16 UTC, gquadrati approved these changes

2024-01-19 16:18 UTC, merged